config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  root to: 'pages#home'

  get "style" => "pages#style"
  get "me" => "pages#me"
  get "me_profile" => "pages#me_profile"

  get 'sign_up_artist' => 'pages#sign_up_artist'
  get 'me_artist' => 'pages#me_artist'
  get 'me_artist_proposals' => 'pages#me_artist_proposals'
  get 'me_artist_winnings' => 'pages#me_artist_winnings'
  get 'me_winnings' => 'pages#me_winnings'


  devise_for :users , controllers: { registrations: "users/registrations", omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :projects, only: [:index, :show, :new, :create, :edit, :update, :destroy]  do
    resources :proposals, only: [:index, :new, :create] do
      resources :reviews, only: [:index,:new, :create, :destroy]
    end
    resources :hidden_projects, only: [:create]
  end

  resources :proposals, only: [:show, :update] do
    resources :messages, only: [:create]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation) %>

  <div class="btn-group-vertical pull-right">
    <%# if conversation.is_trashed?(current_user) %>
      <%#= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
    <%# else %>
      <%#= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>

      <% if conversation.is_unread?(current_user) %>
        <%= link_to 'Unread', conversation_path(conversation), class: 'btn btn-xs btn-info' %>
      <% end %>
    <%# end %>
  </div>

  <p><%= render 'conversations/participants', conversation: conversation %></p>

  <p><%= conversation.last_message.body %>
    <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <%= gravatar_for participant %>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<%= link_to "<<< Retour à mon profil", me_path, class:"btn btn-primary"%>
<br>
<br>
<%= link_to '<<< Nouvelle conversation', new_message_path, class:"btn btn-success" %>


<p>Chatting with
  <%#= render 'conversations/participants', conversation: @conversation %>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><%= @conversation.subject %></div>

  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <div class="media">
          <% message = receipt.message %>
          <div class="media-left">
            <%= gravatar_for message.sender, 45, message.sender.first_name %>
          </div>

          <div class="media-body">
            <h6 class="media-heading"><%= message.sender.first_name %>
              says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
            <%= message.body %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>



<hr>
<h1>Mes Conversations</h1>

Nombre de messages non lus : <%#= @unread_count %>
<div class="row">
  <div class="col-sm-3">
    <ul class="nav nav-pills nav-stacked">
      <%#= mailbox_section 'inbox', @box %>
      <%#= mailbox_section 'sent', @box %>
      <%#= mailbox_section 'trash', @box %>
    </ul>
  </div>

  <div class="col-sm-9">
    <%# if @box == 'trash' %>
      <!-- <p><%#= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %></p> -->
    <%# end %>
    <ul class="list-group">
      <%#= render partial: 'conversations/conversation', collection: @conversations %>
    </ul>

    <%#= will_paginate %>
  </div>
</div>

app/views/conversations/show.html.erb
<%= link_to "<<< Toutes mes conversations", conversations_path %>
<br>
<h1>Conversation</h1>

<p>Chatting with
  <%= render 'conversations/participants', conversation: @conversation %>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><%= @conversation.subject %></div>

  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <div class="media">
          <% message = receipt.message %>
          <div class="media-left">
            <%= gravatar_for message.sender, 45, message.sender.first_name %>
          </div>

          <div class="media-body">
            <h6 class="media-heading"><%= message.sender.first_name %>
              says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
            <%= message.body %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>


<%= form_tag reply_conversation_path(@conversation), method: :post do %>
  <div class="form-group">
    <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Rédigez votre réponse', required: true %>
  </div>
  <%= submit_tag "Envoyer", class: 'btn btn-primary' %>
<% end %>