config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  root to: 'pages#home'

  get "style" => "pages#style"
  get "me" => "pages#me"
  get "me_profile" => "pages#me_profile"

  get 'sign_up_artist' => 'pages#sign_up_artist'
  get 'me_artist' => 'pages#me_artist'
  get 'me_artist_proposals' => 'pages#me_artist_proposals'
  get 'me_artist_winnings' => 'pages#me_artist_winnings'
  get 'me_winnings' => 'pages#me_winnings'


  devise_for :users , controllers: { registrations: "users/registrations", omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :projects, only: [:index, :show, :new, :create, :edit, :update, :destroy]  do
    resources :proposals, only: [:index, :new, :create] do
      resources :reviews, only: [:index,:new, :create, :destroy]
    end
    resources :hidden_projects, only: [:create]
  end

  resources :proposals, only: [:show, :update] do
    resources :messages, only: [:create]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

end

app/models/hidden_project.rb
class HiddenProject < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :proposal

  has_attachments :images, maximum: 5
end

app/models/order.rb
class Order < ActiveRecord::Base
 monetize :amount_cents
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :proposals, dependent: :destroy
  has_many :hidden_projects, dependent: :destroy

  validates :description, :user_id, :style, :price, presence: true
  monetize :price_cents

  scope :recent, -> { where("projects.created_at > ?", DateTime.now - 7.days) }

  has_attachments :photos, maximum: 5

  def self.proposable
    recent.pending
  end

  def self.pending
    all.reject do |p|
      p.proposals.map(&:validated_at).any?(&:present?)
    end
  end

  def self.not_blacklisted(user)
    Project.proposable - user.hidden_projects.includes(:project).map(&:project)
  end

  def ending_at
    created_at + 7.days
  end


end

app/models/proposal.rb
class Proposal < ActiveRecord::Base

  has_attachments :photos, maximum: 5
  belongs_to :user
  belongs_to :project
  has_one :review, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :user_id, :project_id, presence: true

  # scope :pending, -> { where("#{table_name}.validated_at IS NULL") }
  scope :pending, -> { where(validated_at: nil) }
  scope :validated, -> { where("#{table_name}.validated_at IS NOT NULL") }

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :proposal

  validates :content, :rating, :proposal_id, presence: true
  validates :proposal_id, uniqueness: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  has_attachment :avatar
  has_attachments :portfolio_photos, maximum: 30
  has_many :projects, dependent: :destroy
  has_many :proposals, dependent: :destroy
  has_many :received_proposals, through: :projects, source: :proposals
  has_many :hidden_projects, dependent: :destroy
  has_many :messages, dependent: :destroy

  # validates :first_name, :last_name, presence: true
  #
  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create

    @proposal = Proposal.find(params[:proposal_id])
    message = @proposal.messages.new(message_params)
    message.user = current_user
    message.save
    redirect_to @proposal
  end

  private

  def message_params
    params[:message].permit(:content, images: [])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @order = Order.where(state: 'paid').find(params[:id])
  end

  # def create
  #   @project = Project.find(params[:project_id])
  #   order = Order.create!(project_sku: @project.sku, amount: @project.price, state: 'pending')
  #   redirect_to new_order_payment_path(order)
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:home, :sign_up_artist]
  layout "dashboard", only: [:me, :me_winnings, :me_artist, :me_artist_winnings]

  def home
  end

  def me
    @projects = current_user.projects.proposable
  end

  def me_artist
    @projects = Project.not_blacklisted(current_user)
    @proposal = Proposal.new
  end

  def sign_up_artist
    @user = User.new
  end

  def me_artist_winnings
    @proposals = current_user.proposals.validated
    @proposals_not_validated = current_user.proposals - current_user.proposals.validated
  end

  def me_winnings
    @projects = current_user.projects
    render(:layout => "layouts/dashboard")
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new
  end

  def create
    @amount = @order.amount_cents

    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email: params[:stripeEmail]
    )
    # You should store this customer id and re-use it.

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount:       @amount,  # in cents
      description:  "Payment for project #{@order.project_sku} for order #{@order.id}",
      currency:     'eur'
    )

    @order.update(payment: charge.to_json, state: 'paid')

    redirect_to me_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_order_payment_path(@order), notice: "Félicitations, votre concours est lancé   !"
  end

  private

  def set_order
    @order = Order.where(state: 'pending').find(params[:order_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: :new
  before_action :find_project, only: [:show]

  def index
  end

  def new
    @project = Project.new
    if session[:project]
      @project = Project.new(session[:project])
    end
  end

  def create
    @project = current_user.projects.new(project_params)
    order = Order.create!(amount: @project.price, state: 'pending')
    if @project.save
      redirect_to new_order_payment_path(order)
    else
      render :create
    end
  end

  def show
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params[:project].permit(:title, :description, :style, :height, :width, :price, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, size = 30, title = user.first_name)
    image_tag gravatar_image_url(user.email, size: size), title: title, class: 'img-rounded'
  end

  def active_class(link_path)
      current_page?(link_path) ? "active" : ""
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/helpers/hidden_projects_helper.rb
module HiddenProjectsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersoTattoo</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link rel="stylesheet" href="src/css/swipebox.css">
<!--     <script src="lib/jquery-2.0.3.js"></script>
    <script src="src/js/jquery.swipebox.js"></script> -->
  </head>
  <body >

      <%= render 'shared/navbar' %>
      <div class="site-content">
        <%= render 'shared/flashes' %>
        <%= yield %>
      </div>
      <%= yield(:after_js) %>
      <%= render 'shared/footer' %>
      <%= javascript_include_tag 'application' %>
      <%= cloudinary_js_config %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersoTattoo</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body class="app">
    <%= render 'shared/navbar' %>
    <div class="container-fluid app site-content">
      <div class="row">
        <div class="col-sm-2 col-md-2 col-lg-2">
          <% if current_user.artist %>
            <%= render 'shared/sidebar_artist' %>
          <% else %>
            <%= render 'shared/sidebar' %>
          <% end %>
        </div>
        <div class="col-sm-9 col-md-9 col-lg-9">
          <%= render 'shared/flashes' %>
          <%= yield %>
        </div>
      </div>

    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- Banner with search buttons  -->
<div class="banner" style="background: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= asset_path "tatoo.jpg"%>);">
  <div class="banner-content">
  <div class="container">
    <h1>Réalisez le tatouage de vos rêves</h1>
    <p>Lancez votre coucours et obtenez votre tatouage personnalisé dessiné par les meilleurs artistes du monde entier</p>
    <!-- <a class="btn btn-primary btn-lg">GET IT</a> -->
</div>

    <div class="home-cta">
      <% if user_signed_in? %>

          <% if current_user.artist == false %>
            <%= link_to "J'envoie mon projet", me_path, class: "btn-cta-customer" %>
          <% else %>
            <%= link_to "J'envoie mon projet", me_artist_path, class: "btn-cta-customer" %>
          <% end %>
          <% if current_user.artist == false %>
            <%= link_to "Je suis un artiste", me_path, class: "btn-cta-artist" %>
          <% else %>
            <%= link_to "Je suis un artiste", me_artist_path, class: "btn-cta-artist" %>
          <% end %>

        <% else %>

          <%= link_to "J'envoie mon projet", new_project_path, class: "btn-cta-customer" %>
          <%= link_to "Je suis un artiste", sign_up_artist_path, class: "btn-cta-artist" %>

      <% end %>
    </div>
  </div>
</div>

app/views/pages/me.html.erb
<div class="container">
  <h1>Mes projets</h1>
  <%= link_to "Créer un projet", new_project_path, class:"btn btn-success"%>
  <div class="row">
    <% @projects.each do |project| %>
    <div class="col-xs-12 col-sm-6 ">
      <div class="card" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path project.photos.first.path if project.photos.any? %>')">

        <div class="card-description">
          <h3><%= project.title %></h3>
          <p><i><%= project.style %></i></p>
          <h2>
            <%= link_to pluralize(project.proposals.count,'proposition'), project_proposals_path(project), {class:"label label-success text-align-center"} if project.proposals.count>0 %>
          </h2>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/pages/me_artist.html.erb
<!-- LA PARTIE PROJETS  -->
  <h1>Tous les projets</h1>
  <div class="row">
    <% @projects.each do |project| %>
      <div class="col-xs-12 col-sm-6" id="card-project-<%= project.id %>">
        <div class="card" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path project.photos.first.path if project.photos.any? %>')">
          <div class="card-category">
            <% if project.user.avatar? %>
              <%= cl_image_tag project.user.avatar.path, size: "30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <%else%>
              <%= cl_image_tag "https://freeiconshop.com/files/edd/person-solid.png", size: "30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
              <% end %>
            <%= project.user.first_name%>
          </div>

          <!-- TO MOVE SOMEWHERE ELSE -->
          <% content_for :after_js do %>
            <script>
              var endingAt<%= project.id %> = moment('<%= project.ending_at %>');

              var currentTime = moment.utc();
              var diffTime<%= project.id %> = endingAt<%= project.id %> - currentTime;
              var duration<%= project.id %> = moment.duration(diffTime<%= project.id %>);
              var interval = 1000;

              setInterval(function(){
                duration<%= project.id %> = moment.duration(duration<%= project.id %> - interval, 'milliseconds');
                $('#project-countdown-<%= project.id %>').text(duration<%= project.id %>.days() + "j - " + duration<%= project.id %>.hours() + ":" + ('00' + duration<%= project.id %>.minutes()).slice(-2) + ":" + ('00' + duration<%= project.id %>.seconds()).slice(-2))
              }, interval);
            </script>
          <% end %>
          <!-- NO KIDDING -->

          <div id="project-countdown-<%= project.id %>" class="countdown"></div>
          <div class="card-description">
            <h2>
              <%= project.title %>
              <%= link_to "", "#", class:"card-description card-link", data: { toggle: "modal", target: "#modal-project-#{project.id}" } %>

            </h2>

          </div>
          <span class="label label-success"><%= humanized_money (project.price) %> €</span>

          <%= link_to project_hidden_projects_path(project), method: :post, class: "card-hide", data: {confirm: 'Sûr de cacher ce projet ? Cette action est définitive.'}, remote: true do %>
            <i class="fa fa-eye-slash"></i> Cacher ce projet
          <% end %>
        </div>
      </div>

      <div class="modal fade" id="modal-project-<%= project.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <h4 class="modal-title" id="myModalLabel">Ma proposition</h4>
            </div>
            <div class="modal-body">
              <%= simple_form_for [project, @proposal] do |f| %>
                <%= f.input :content, label: 'Explication', placeholder: 'Expliquez pourquoi vous avez décidé de réaliser cette superbe esquisse' %>
                <%= f.input :photos, label: 'Visuels', as: :attachinary %>
                <%= f.button :submit, "Soumettre ma proposition", class: "btn btn-success btn-block"%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/pages/me_artist_proposals.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="tab active">
    <a data-target="#accepted" href="#accepted">
      Mes propositions acceptées
    </a>
  </li>
  <li role="presentation" class="tab">
    <a data-target="#pending" href="#pending">
      Mes propositions en attente
    </a>
  </li>
</ul>

<!-- ACCEPTED PROPOSALS -->
​
<div class="container">
  <div class="row">
    <% @proposals.each do |proposal| %>
      <%= proposal.content %>
      <%= proposal.validated_at %>
      <%= proposal.project.user.first_name %>
      <%= link_to "Voir", proposal_path(proposal) %>
      <br>
    <% end %>
  </div>
</div>
​
 <!-- PENDING PROPOSALS  -->

<div class="tab-content" data-target="#accepted" id="accepted">
  <div class="well">
  <h1 class="text-center">Mes propositions confirmées </h1>
      <div class="container">
       <div class="row">
         <div class="col-xs-12 col-sm-6">
         <% current_user.proposals.each do |proposal| %>
           <div class="card" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('assets/images/project.jpg')">
           <div class="card-description">
             <p><%= proposal.content %></p>
           </div>
           <%= link_to "Proposal", proposal_path(proposal), {class: "card-link"} %>
           </div>
         <% end %>
         </div>
       </div>
      </div>
    </div>
</div>

app/views/pages/me_artist_winnings.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="tab active">
    <a data-target="#accepted" href="#">
      Mes propositions acceptées
    </a>
  </li>
  <li role="presentation" class="tab">
    <a data-target="#pending" href="#">
      Mes propositions en attente
    </a>
  </li>
</ul>

<!-- ACCEPTED PROPOSALS -->
​<div class="tab-content" id="accepted">
  <div class="well ">
    <div class="row">
        <% @proposals.each do |proposal| %>
        <div class="col-xs-12 col-sm-6">
          <div class="card" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path proposal.photos.first.path if proposal.photos.any? %>')">
            <div class="card-description">
              <%= proposal.content %>
              <br>
              <br>
              <%= l(proposal.validated_at.to_date, format: :default) %>
              <%= link_to "", proposal_path(proposal), class:"card-description card-link"%>
            </div>
            <div class="card-category">
              <% if proposal.project.user.avatar? %>
                <%= cl_image_tag proposal.project.user.avatar.path, size: "30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
              <%else%>
              <%= cl_image_tag "https://freeiconshop.com/files/edd/person-solid.png", size: "30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
              <% end %>
              <%= proposal.project.user.first_name %>
            </div>
            <span class="label label-success"><%= humanized_money proposal.project.price %> €</span>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
​
 <!-- PENDING PROPOSALS  -->
<div class="tab-content hidden" id="pending">
  <div class="well ">
    <div class="row">
      <% @proposals_not_validated.each do |proposal| %>
        <div class="col-xs-12 col-sm-6">
          <div class="card" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path proposal.photos.first.path if proposal.photos.any? %>')">
            <div class="card-description">
              <%= proposal.content %>
            </div>
            <div class="card-category">
              <% if proposal.project.user.avatar? %>
                <%= cl_image_tag proposal.project.user.avatar.path, size: "30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
              <%else%>
                <%= cl_image_tag "https://freeiconshop.com/files/edd/person-solid.png", size: "30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
              <% end %>
              <%= proposal.project.user.first_name %>
            </div>
            <span class="label label-success"><%= humanized_money (proposal.project.price) %> €</span>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/me_winnings.html.erb
<div class="tab-content" id="accepted">
  <div class="well ">
    <div class="row">
      <% @projects.each do |project| %>
        <% p = project.proposals.validated %>
        <% p.each do |proposal| %>
          <div class="col-xs-12 col-sm-6">
              <div class="card" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path proposal.photos.first.path if proposal.photos.any? %>')">

                <div class="card-description">
                  <%= proposal.content %>
                  <br>
                  <br>
                  <%= l(proposal.validated_at.to_date, format: :default) %>
                  <%= link_to "", proposal_path(proposal), class:"card-description card-link"%>
                </div>

                <div class="card-category">
                  <% if proposal.user.avatar? %>
                    <%= cl_image_tag proposal.user.avatar.path, size: "30x30", crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
                  <%else%>
                  <%= cl_image_tag "https://freeiconshop.com/files/edd/person-solid.png", size: "30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
                  <% end %>
                  <%= proposal.user.first_name %>
                </div>
                <span class="label label-success"><%= humanized_money (proposal.project.price)%> €</span>
              </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/sign_up_artist.html.erb
<div class="banner" style="background: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://drscdn.500px.org/photo/140800209/q%3D80_h%3D450/74d561073c655da33872723a631c0151');">
  <div class="container">
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4 card-devise">
        <div class="light-well">
          <h3 class= "page-header black-policy text-center"><%= t('.sign_up', :default => "Inscription" )%></h3>
          <br>
            <%= simple_form_for(@user, as: :user, url: user_registration_path) do |f| %>
              <%= f.error_notification %>

              <div class="form-inputs black-policy">
                <div class="form-group">
                  <%= f.email_field :email, autofocus: true, placeholder: "Email ", class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.password_field :password, autocomplete: "off", placeholder: "Mot  de passe", class: "form-control" %>
                 </div>

                <div class="form-group">
                  <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: "Confirmer le mot de passe", class: "form-control" %>
                  <% if @validatable %>
                    <p class="help-block"><%= @minimum_password_length %> characters minimum</p>
                  <% end %>
                </div>

                <%= f.input :artist, as: :hidden, input_html: { value: true } %>
              </div>

              <div class="form-actions">
                <%= f.button :submit, "Inscription", class: "btn btn-success form-control" %>
              </div>

            <% end %>
        <br>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <!-- <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
 -->
    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <% if current_user.artist == false %>
        <%= link_to "#{current_user.first_name}", me_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% else %>
        <%= link_to "#{current_user.first_name}", me_artist_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
        <% if user_signed_in? and current_user.avatar %>
          <%= cl_image_tag current_user.avatar.path, size: "30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <%else%>
           <%= cl_image_tag "https://freeiconshop.com/files/edd/person-solid.png", size: "30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to root_path do %>
              <i class="fa fa-home"></i>  <%= t ".profile", default: "Accueil" %>
              <% end %>
            </li>
            <li>
              <%= link_to me_path do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profil" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Deconnexion" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>
      <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "btn-medium" %>
    <% end %>

 </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to root_path do %>
            <i class="fa fa-home"></i>  <%= t ".profile", default: "Accueil" %>
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "Profil" %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Deconnexion" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<ul class="nav nav-pills nav-stacked">
  <li role="presentation" class="<%= active_class(me_path)%>">
    <%= link_to "Mes projets", me_path %>
  </li>
  <li role="presentation" class="<%= active_class(me_winnings_path)%>">
    <%= link_to "Mes propositions", me_winnings_path %>
  </li>
  <li role="presentation" class="<%= active_class(edit_user_registration_path)%>">
    <%= link_to "Mon profil", edit_user_registration_path %>
  </li>
</ul>

app/views/shared/_sidebar_artist.html.erb
<ul class="nav nav-pills nav-stacked">
  <li role="presentation" class="<%= active_class(me_artist_path)%>">
    <%= link_to "Tous les projets", me_artist_path %>
  </li>
  <li role="presentation" class="<%= active_class(me_artist_winnings_path)%>">
    <%= link_to "Mes propositions", me_artist_winnings_path %>
  </li>
  <li role="presentation" class="<%= active_class(edit_user_registration_path)%>">
    <%= link_to "Mon profil", edit_user_registration_path %>
  </li>
</ul>