config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  root to: 'pages#home'

  get "style" => "pages#style"
  get "me" => "pages#me"
  get "me_profile" => "pages#me_profile"

  get 'sign_up_artist' => 'pages#sign_up_artist'
  get 'me_artist' => 'pages#me_artist'
  get 'me_artist_proposals' => 'pages#me_artist_proposals'
  get 'me_artist_winnings' => 'pages#me_artist_winnings'
  get 'me_winnings' => 'pages#me_winnings'


  devise_for :users , controllers: { registrations: "users/registrations", omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :projects, only: [:index, :show, :new, :create, :edit, :update, :destroy]  do
    resources :proposals, only: [:index, :new, :create] do
      resources :reviews, only: [:index,:new, :create, :destroy]
    end
    resources :hidden_projects, only: [:create]
  end

  resources :proposals, only: [:show, :update] do
    resources :messages, only: [:create]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :proposals, dependent: :destroy
  has_many :hidden_projects, dependent: :destroy

  validates :description, :user_id, :style, :price, presence: true
  monetize :price_cents

  scope :recent, -> { where("projects.created_at > ?", DateTime.now - 7.days) }

  has_attachments :photos, maximum: 5

  def self.proposable
    recent.pending
  end

  def self.pending
    all.reject do |p|
      p.proposals.map(&:validated_at).any?(&:present?)
    end
  end

  def self.not_blacklisted(user)
    Project.proposable - user.hidden_projects.includes(:project).map(&:project)
  end

  def ending_at
    created_at + 7.days
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: :new
  before_action :find_project, only: [:show]

  def index
  end

  def new
    @project = Project.new
    if session[:project]
      @project = Project.new(session[:project])
    end
  end

  def create
    @project = current_user.projects.new(project_params)
    order = Order.create!(amount: @project.price, state: 'pending')
    if @project.save
      redirect_to new_order_payment_path(order)
    else
      render :create
    end
  end

  def show
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params[:project].permit(:title, :description, :style, :height, :width, :price, photos: [])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/new.html.erb
<div class="banner" style="background: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://drscdn.500px.org/photo/83060751/q%3D80_h%3D450/291b840e7d1ddd12bfe3c44d70f19222');">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2 card-devise card-view">
        <div class="light-well">
          <h3 class="black-policy">Description de mon projet<br>
            <small>Lancer mon concours pour obtenir mon tatouage personnalisé</small>
          </h3>
            <%= simple_form_for @project do |f| %>
              <br>
              <%= f.input :title, label:false, placeholder: "Titre Ex. : une chouette sur une branche de bambou" %>
              <%= f.input :description, label:false, placeholder: "Description Ex. : la chouette doit être le sujet principal, avec des yeux transpersants" %>

              <%= f.input :style, label:false, collection: ["Style", "Japonais", "Mots / Calligraphie", "Dessin", "Graphique / abstrait", "Tribal / Maori", "Bio-méchanique", "Dotwork-Linework / Mandala", "New school / Old school", "Watercolor"], selected: "Style" %>
              <h3 class="text-center black-policy">Dimensions du Tattoo</h3>
                <div class="row">
                <div class="col-xs-3 col-xs-offset-2">

                  <%= f.input :height, label:false, placeholder:"hauteur" %>
                </div>
                <div class="col-xs-3 col-xs-offset-2">
                  <%= f.input :width, label:false, placeholder:"largeur" %>

                </div>
                </div>
                <h3 class=" black-policy">Images d'inspiration</h3>
                <div class="classement">
                  <%= f.input :photos, label:false, as: :attachinary %>
                </div>
                <%= f.input :price, label:false, collection: ["Choisir mon offre","99€", "199€ ", "299€"], selected:"Choisir mon offre" %>
                <div class="classement">
                  <%= f.button :submit, "Soumettre mon projet" , class: "btn btn-success btn-block" %>
                </div>
                <br>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container">

  <h1><%= @project.title %></h1>

  <p><%= @project.description %></p>
  <p><%= @project.style %></p>
  <p><%= @project.height %></p>
  <p><%= @project.width %></p>
  <p><strong>Amount: <%= humanized_money_with_symbol(@project.price) %></strong></p>


<%= form_tag orders_path do %>
  <%= hidden_field_tag 'project_id', @project.id %>
  <%= submit_tag 'Purchase' %>
<% end %>

</div>