config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  root to: 'pages#home'

  get "style" => "pages#style"
  get "me" => "pages#me"
  get "me_profile" => "pages#me_profile"

  get 'sign_up_artist' => 'pages#sign_up_artist'
  get 'me_artist' => 'pages#me_artist'
  get 'me_artist_proposals' => 'pages#me_artist_proposals'
  get 'me_artist_winnings' => 'pages#me_artist_winnings'
  get 'me_winnings' => 'pages#me_winnings'


  devise_for :users , controllers: { registrations: "users/registrations", omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :projects, only: [:index, :show, :new, :create, :edit, :update, :destroy]  do
    resources :proposals, only: [:index, :new, :create] do
      resources :reviews, only: [:index,:new, :create, :destroy]
    end
    resources :hidden_projects, only: [:create]
  end

  resources :proposals, only: [:show, :update] do
    resources :messages, only: [:create]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new
  end

  def create
    @amount = @order.amount_cents

    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email: params[:stripeEmail]
    )
    # You should store this customer id and re-use it.

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount:       @amount,  # in cents
      description:  "Payment for project #{@order.project_sku} for order #{@order.id}",
      currency:     'eur'
    )

    @order.update(payment: charge.to_json, state: 'paid')

    redirect_to me_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_order_payment_path(@order), notice: "Félicitations, votre concours est lancé   !"
  end

  private

  def set_order
    @order = Order.where(state: 'pending').find(params[:order_id])
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/new.html.erb
<div class="banner" style="background: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://drscdn.500px.org/photo/109541019/q%3D80_h%3D450/9aa2b5b2b010269d3266c958cbaa8fe6');">
  <div class="container">
      <div class="col-sm-4 col-sm-offset-4 card-devise">
        <div class="black-policy">
          <h3>Satisfait ou remboursé</h3>
          <hr>

          <div style="text-align:left;">
            <i class="fa fa-check-square-o" style="color:green;"></i> Votre brief n'a pas besoin d'être parfait. Vous pourrez le modifier plus tard.
            <br>
            <br>
            <i class="fa fa-check-square-o" style="color:green;"></i> Vous pourrez apporter votre design à n'importe quel tatoueur. Vous ne savez pas où aller ? Nous vous aidons à le trouver.
            <br>
            <br>
            <i class="fa fa-check-square-o" style="color:green;"></i> Si aucun design ne vous plaît, nous vous remboursons.
          </div>
         </div>
         <br>
          <%= simple_form_for :payment, url: order_payments_path(@order) do |f| %>
            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" id="stripe-auto"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-image="<%= asset_path "tatoo.jpg"%>"
              data-name="PersoTattoo"
              data-description="<%= @order.project_sku %>"
              data-email= "<%= current_user.email%>"
              data-amount="<%= @order.amount_cents %>"
              data-currency="EUR">
            </script>
          <% end %>
        </div>
   </div>
</div>